# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  backend:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x    
    - name: Build
      run: dotnet build
      working-directory: code/backend/TA-API
  frontend-ng:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - name: Install packages
      run: npm install
      working-directory: code/frontend/ta-web
    - name: Build
      run: npm test
      working-directory: code/frontend/ta-web
  frontend-react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - name: Install packages
      run: npm install
      working-directory: code/frontend/ta-web-react
    - name: Build
      run: npm build
      working-directory: code/frontend/ta-web-react
